version: "3"

services:
  localstack:
    image: localstack/localstack:1.4.0
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - DEFAULT_REGION=ap-northeast-1
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - localstack:/tmp/localstack/
      - './localstack_init:/docker-entrypoint-initaws.d'

volumes:
  localstack:
